.changes/unreleased/Added-20240722-051924.yaml
.goreleaser.yml

This was intended in the last release but was missed.

release: Add Linux ARM binaries

---

doc/src/index.md

There's a small typo in index.md.
Fix it.

Fix Docs Spelling

---

doc/src/guide/pr.md

Mention the short form `-c` of the `--fill` flag in the documentation.

doc: Add note about #301

---

.changes/unreleased/Fixed-20240729-201902.yaml
branch_create.go
testdata/script/branch_create_already_exists.txt
testdata/script/branch_create_generate_name_conflict.txt

Handle the case where the requested branch or the auto-generated branch
name already exists.
Refs #307

branch create: Handle branch already exists

---

doc/src/guide/branch.md
doc/src/guide/pr.md

Add a note on giving branches descriptive names,
and the ability to auto-generate them.

doc/guide: Add note on branch naming

---

.changes/unreleased/Added-20240806-200004.yaml
doc/src/cli/shorthand.md
internal/cli/shorthand/expand.go
internal/cli/shorthand/expand_test.go
internal/spice/config.go
internal/spice/config_test.go
main.go
testdata/script/custom_shorthands.txt

config: Support custom shorthands

---

branch_create.go

Encapsulate logic for committing staged changes
into a separate function.
This is going to make it easier to add commit opt-out.

refac(branch create): Extract commit logic

---

branch_submit.go
branch_untrack.go
dumpmd.go
internal/forge/github/change_meta.go
internal/forge/shamhub/change_meta.go
internal/spice/restack.go
internal/spice/template.go
repo_sync.go

all: Drop outdated TODOs

---

repo_sync.go

Separate searching for branches to delete from actually deleting them.
This will allow re-using the same logic to delete branches
that were merged for unsupported forges.
This is also necessary to later make the deletion logic smarter
to delete branches in the correct order.

refac(repo sync): split out branch deletion logic

---

.goreleaser.yml

it should be GPL-3.0-or-later rather than GPL-3.0

chore: update GPL license ref

---

submit.go

UpdateBranch is being deleted in favor of BranchTx.
[skip changelog]: No user-facing changes.

submit: Use BranchTx to update comment metadata

---

.changes/unreleased/Fixed-20240927-221256.yaml
branch_fold.go
branch_split.go
branch_submit.go
branch_track.go
internal/spice/branch.go
internal/spice/mock_service_test.go
internal/spice/onto.go
internal/spice/restack.go
internal/spice/service.go
internal/spice/state/branch.go
internal/spice/state/branch_test.go
internal/spice/state/store_test.go
testdata/script/branch_fold_simple_errors.txt
testdata/script/branch_fold_updates_upstacks.txt

[skip changelog]: No user facing changes

all: Switch uses of UpdateBranch to BranchTx

---

.github/workflows/doc.yml
doc/uv.lock

Upgrade to the latest version of uv
and various Python packages.

doc: Upgrade uv, mkdocs

---

testdata/script/auth_prompt_forge.txt
testdata/script/branch_checkout_prompt_trunk.txt
testdata/script/branch_checkout_track_prompt.txt
testdata/script/branch_delete_unmerged.txt
testdata/script/branch_rename_prompt.txt
testdata/script/branch_split_prompt.txt
testdata/script/branch_submit_multiple_pr_templates.txt
testdata/script/branch_submit_pr_template_no_body.txt
testdata/script/branch_submit_remote_prompt.txt
testdata/script/repo_init_prompt_multiple_local.txt
testdata/script/repo_init_prompt_upstream.txt
testdata/script/repo_init_remote_prompt.txt
testdata/script/repo_sync_external_pr_head_mismatch.txt
testdata/script/top_multiple_prompt.txt
testdata/script/up_down_top_bottom_prompt.txt
testdata/script/up_multiple_prompt.txt

Switch a few of the test scripts that use prompts
to the new RobotView introduced in #480.
These tests can now run on Windows.

test scripts: use robot view for testing prompts

---

internal/forge/gitlab/auth.go
internal/forge/gitlab/auth_test.go
internal/forge/gitlab/client.go
internal/forge/gitlab/comment_test.go
internal/forge/gitlab/forge.go

This pull request introduces support for GitLab CLI authentication.

feat: Add GitLab CLI authentication option

---

README.md
doc/hooks/badge.py
doc/hooks/replace.py
doc/includes/captures/forge-prompt.txt
doc/mkdocs.yml
doc/src/cli/config.md
doc/src/faq.md
doc/src/guide/branch.md
doc/src/guide/concepts.md
doc/src/guide/cr.md
doc/src/guide/internals.md
doc/src/guide/limits.md
doc/src/img/stack-comment-glab.png
doc/src/index.md
doc/src/recipes.md
doc/src/setup/auth.md
doc/src/start/stack.md
doc/src/start/submit.md
internal/forge/gitlab/forge.go

Update documentation website to reflect the new GitLab support
from #477.
refs #485

doc: Update for GitLab support

---

internal/forge/shamhub/submit.go

Don't allow submitting changes where the base or head branch
hasn't been pushed yet.
[skip changelog]: No user-facing changes.

shamhub: Reject submits for unknown branches

---

internal/ui/input.go
internal/ui/select.go
internal/ui/widget/branch_select.go
testdata/script/branch_checkout_prompt.txt
testdata/script/branch_delete_prompt_untracked.txt
testdata/script/branch_split_reassign_submitted.txt
testdata/script/branch_submit_long_body.txt
testdata/script/branch_submit_pr_template_prompt.txt
testdata/script/branch_submit_recover_prepared.txt

Port more of the integration tests that currently rely on with-term
to the new RobotView mechanism.
The couple remaining with-term tests are harder to port to RobotView
as they rely on more advanced functionality.

Move more integration tests to RobotView

---

internal/must/must.go

must: Generalize to accept type aliases

---

DESIGN.md

Explain a little of how #508 works in DESIGN for future reference.

DESIGN: Add notes on merged downstack history

---

internal/termtest/with_term.go
internal/ui/uitest/script.go
testdata/script/commit_split.txt

Fixes a flaky test in commit_split while at it.

test: Generalize with-term

---

internal/forge/shamhub/cli.go
internal/forge/shamhub/merge.go
testdata/script/repo_sync_squash_merged.txt

Adds a test that squash-merges a shamhub PR
and verifies that repo sync behaves as expected.

test(repo sync): verify squash-merge behavior

---

Makefile

This is a leftover from pre-Go 1.23 work on this project.

make: Drop unused GOEXPERIMENT

---

testdata/script/repo_sync_conflict.txt

test: verify 'repo sync' handles conflicts

---

doc/src/setup/auth.md

doc: Adjust Self-Hosted GitHub instructions

---

.changes/unreleased/Added-20250219-110433.yaml
CONTRIBUTING.md
branch.go
branch_checkout.go
doc/includes/cli-reference.md
doc/src/cli/config.md
internal/git/branch.go
internal/git/branch_test.go
internal/spice/guess.go
internal/spice/mock_service_test.go
internal/spice/service.go
repo_sync.go
shell_completion.go
testdata/script/branch_checkout_prompt_sort_by_committerdate.txt

feat(branch): add sort option for branch list

---

internal/git/gittest/fixture.go

testscript.Params.Files support was added in a prior version,
obviating the need to set up a temporary directory with just the script.
We still use it to run scripts from in-memory strings,
but otherwise, we can rely on the Files parameter for the work here.

chore(gittest): Use testscript.Params.Files

---

.github/workflows/ci.yml
tools/ci/install-git/main.go

Port the step to build and install a specific version of Git from source
to Go from bash.

ci(tools): Port install Git step to Go

---

internal/fixturetest/fixturetest.go
internal/forge/gitlab/client.go
internal/forge/shamhub/cli.go
internal/git/gittest/fixture.go
internal/graphqlutil/error.go
internal/spice/config.go
internal/spice/state/storage/git.go
internal/text/dedent.go
internal/ui/confirm.go
internal/ui/uitest/robot.go
internal/ui/uitest/script.go
internal/ui/widget/branch_select.go

```
go run golang.org/x/tools/gopls/internal/analysis/modernize/cmd/modernize@latest -fix -test ./...
```
Ref: https://github.com/golang/tools/releases/tag/gopls%2Fv0.18.0

all: run gopls modernize over the code

---

.changes/unreleased/Added-20250313-210351.yaml
doc/includes/cli-reference.md
doc/src/cli/config.md
doc/src/setup/auth.md
internal/forge/gitlab/forge.go
internal/forge/gitlab/forge_test.go

Add gitlab-api-url override

---

mise.lock

Update dependencies with 'mise upgrade'.

deps: mise upgrade

---

internal/git/branch.go
internal/git/branch_test.go

Add support to git/LocalBranches to filter branches by patterns.
This will be used to determine whether a specific branch is checked out
in another worktree.

git/LocalBranches: add support for filtering by pattern

---

mise.lock

mise upgrade

---

internal/handler/track/handler_test.go

Add tests for base branch guessing logic in the track handler.

test(track): base guessing logic

---

internal/handler/restack/handler.go
internal/handler/restack/mocks_test.go
internal/handler/restack/repo.go
repo_restack.go
upstack_restack.go

refac(repo restack): move logic to restack.Handler

---

internal/spice/branch_graph.go
internal/spice/branch_graph_test.go

internal/BranchGraph: add more operations

---

.changes/unreleased/Added-20250808-191933.yaml
doc/includes/cli-reference.md
doc/src/cli/config.md
internal/handler/submit/form.go
internal/handler/submit/handler.go
testdata/script/branch_submit_default_template.txt
testdata/script/branch_submit_template_config.txt

Add an option to configure the default template file

submit: allow default template to be configured

---

doc/mkdocs.yml
doc/src/guide/troubleshooting.md
doc/uv.lock

Add a troubleshooting section for common issues.
Includes issue from #783 and the fix.
Resolves #783

doc: add troubleshooting section

---

internal/git/rebase_wt_test.go

TestRebase_deliberateInterrupt flaked in some environments
because GIT_EDITOR was set, which caused it to use a command
that was not mockedit.

fix(rebase): flaky TestRebase_deliberateInterrupt

---

branch_create.go
branch_onto.go
branch_split.go
commit_fixup.go
internal/forge/github/integration_test.go
internal/forge/gitlab/integration_test.go
internal/forge/shamhub/fork_test.go
internal/git/branch_test.go
internal/git/branch_wt.go
internal/handler/checkout/handler.go
internal/handler/checkout/handler_test.go
internal/handler/checkout/mocks_test.go
internal/handler/delete/handler.go
internal/handler/fixup/handler_test.go
internal/handler/restack/branch_test.go
internal/handler/restack/handler.go
internal/handler/restack/handler_test.go
internal/handler/restack/mocks_test.go
internal/handler/squash/handler.go
internal/handler/squash/handler_test.go
internal/handler/squash/mocks_test.go
internal/handler/sync/handler.go
rebase_continue.go
repo_restack.go

git: rename Checkout to CheckoutBranch

---

branch_track.go
internal/handler/checkout/handler.go
internal/handler/checkout/handler_test.go
internal/handler/checkout/mocks_test.go
internal/handler/track/branch.go
internal/handler/track/branch_test.go
internal/handler/track/handler.go

Renames AddBranch to TrackBranch to better reflect its purpose.

refac(track/Handler): AddBranch => TrackBranch
