.changes/unreleased/Changed-20240723-091300.yaml
main.go

This commit is a small change to the cli that runs the --help command when no args are present.

feat(cli): show help command when no command present

---

.changes/unreleased/Changed-20240723-091300.yaml
main.go
testdata/script/no_args.txt

Follow up to #278
We present --help when invoked without any arguments,
but that's still an invalid invocation,
so we should fail with a non-zero exit code.

Use a non-zero exit code for 'gs' without arguments

---

.changes/unreleased/Fixed-20240722-184205.yaml
branch_submit.go
testdata/script/branch_submit_no_publish.txt

Part of the code responsible for updating the comments in PRs
will print a warning when --no-publish is used.
Resolves #277

branch submit: Fix "branch is not tracked" warning with --no-publish

---

.changes/unreleased/Added-20240722-195530.yaml
.changes/unreleased/Fixed-20240722-200542.yaml
branch_submit.go
doc/includes/cli-reference.md
doc/src/guide/pr.md
internal/git/push.go
testdata/script/branch_submit_force_push.txt
testdata/script/branch_submit_needs_restack.txt

This will force push even if there are conflicts.
In implementing this, also found a bug where --force-with-lease was
called with the wrong hash, so it would always overwrite what the remote
had.
Resolves #275

branch submit: Add --force flag

---

.github/workflows/doc.yml

Don't just install an unpinned "latest" pipenv.
Pin to a fixed version.

ci/doc: Freeze pipenv version

---

.goreleaser.yml

Fix the AUR binary name: it's 'gs', not git-spice,
and add ghostscript as a conflicting package
because it also provides a 'gs' binary.
[skip changelog]: Issue fixed in existing AUR manually.

release/AUR: Fix binary name

---

.changes/unreleased/Fixed-20240723-070944.yaml
.changes/unreleased/Fixed-20240723-071006.yaml
.changes/unreleased/Fixed-20240723-072206.yaml
branch_submit.go
doc/includes/cli-reference.md
downstack_edit.go
editor.go
internal/execedit/editor.go
internal/git/var.go
internal/spice/stack_edit.go
internal/ui/open_editor.go
stack_edit.go
testdata/script/branch_submit_use_git_editor.txt

We were using `$EDITOR` to fill in the PR body.
This is not correct.
We should use the output of 'git var GIT_EDITOR'.
The Git editor (and `$EDITOR`) are allowed to be shell commands,
not just executable names. Handle that correctly too.
Lastly, re-use the same logic for stack edit and downstack edit.
Resolves #274

fix: Use 'git var GIT_EDITOR' for PR body

---

.changes/unreleased/Fixed-20240723-172718.yaml
commit_split.go
testdata/script/commit_split_incomplete_rollback.txt

When the user cancels the commit split with Ctrl-C,
our main() cancels the context we're operating with.
We were previously attempting to reuse that same context
for the rollback command.
This obviously caused the rollback to fail with "context canceled".
Fix this by giving the rollback a still-valid context.
Resolves #291

commit split: Don't break on Ctrl-C

---

internal/secret/stash_test.go
internal/secret/unsafe.go
internal/secret/unsafe_test.go

Adds a stash that stores secrets in plain text in a local JSON file.
For safety and visibility, advertises the location of the stash
the first time it's written to.

secret: Add Unsafe stash

---

internal/secret/fallback.go
internal/secret/stash_test.go

Adds a secret storage that will allow a primary and secondary store.
The secondary store is used only if the primary is broken
for non-expected reasons.
Notably, LoadSecret returning ErrNotFound is not an unexpected breakage.

secret: Add Fallback stash

---

.changes/unreleased/Added-20240723-222630.yaml
doc/src/faq.md
doc/src/guide/internals.md
doc/src/setup/auth.md
doc/src/setup/shell.md
internal/secret/unsafe.go
main.go
script_test.go
testdata/script/auth_unsafe_storage.txt

Headless Linux machines (Docker environments and the like)
can't easily get access to GNOME Keyring or other secure storage.
In such cases, we should fall back to plain text storage,
but warn the user about it so they know what's going on.
Resolves #293

auth: use unsafe secret stash if secure is unavailable

---

doc/src/setup/auth.md

In #293, @messense confirmed that these settings work on GHES.
Adding to documentation for others who need direction.

doc/auth: Mention GitHub Enterprise

---

.changes/unreleased/Removed-20240724-120607.yaml
branch_delete.go
doc/includes/cli-reference.md

In interactive mode, the command will prompt for force-deletion
regardless.
In non-interactive mode, the long-form isn't much of a burden.

branch delete: Drop short-form --force flag

---

.changes/unreleased/Added-20240724-121944.yaml
branch_submit.go
doc/includes/cli-reference.md
testdata/script/upstack_submit_main.txt

I use the `--fill` option a lot. Can we get a short flag for it?

branch submit: Add -c short form for --fill

---

internal/termtest/with_term.go

There's a race on closing the file and stopping to read from it.
It's not a failure to have a closed pty here instead of EOF.
[skip changelog]: not user facing

termtest: Don't fail on 'file already closed'

---

internal/secret/insecure.go
internal/secret/insecure_test.go
internal/secret/stash_test.go
main.go
testdata/script/auth_insecure_storage.txt

'insecure' is a more accurate representation of the stash.
[skip changelog]: not user facing

chore: Rename UnsafeStash to InsecureStash

---

.changes/unreleased/Fixed-20240729-192426.yaml
branch_submit.go
internal/ui/open_editor.go
testdata/script/branch_submit_no_editor.txt
testdata/script/branch_submit_use_git_editor.txt

Currently `OpenEditor` does not take into account when the $EDITOR env var is not set - in which case the Command just errors out and continues to ask the next question on whether to mark the PR as draft.
The fix is quite simple - add a case for checking if the env var is set and return tea.Quit if that's the case. 
Fix #310.

Check if $EDITOR env var is empty

---

.changes/unreleased/Fixed-20240729-194855.yaml
branch_checkout.go
branch_submit.go
branch_track.go

The message instructing users to run 'gs branch restack'
advises the form:
gs branch restack <branch>
This is a leftover from when the argument was positional.
It is now a flag; fix the mssage to match.
Resolves #308

all: Fix 'gs branch restack' message

---

.changes/unreleased/Fixed-20240729-210429.yaml
branch_create.go
testdata/script/issue307_branch_create_cannot_create.txt

If branch creation fails for any reason,
reset to the state before commit before checking out original branch.
This will prevent those committed changes from being lost.
Resolves #307

branch create: Don't lose data on branch creation error

---

dumpmd.go
internal/cli/shorthand/builtin.go
internal/cli/shorthand/builtin_test.go
internal/cli/shorthand/expand.go
internal/cli/shorthand/expand_test.go
main.go

Extracts support for adding shorthands to the CLI
into a separate package with composable "Source" types
for providing the expansions.
We start with only a built-in source, with rooom for more in the future.
This also ends up testing the shorthand expansion thoroughly.

refac: Extract shorthand support into a separate package

---

.changes/unreleased/Added-20240807-053124.yaml
doc/hooks/cliref.py
doc/includes/cli-reference.md
doc/src/cli/config.md
dumpmd.go
log.go
testdata/script/config_log_all.txt

It didn't sit right to land the configuration system change
without actual configuration options.
Add the ability to make the `-a` flag in `gs ll` and `gs ls`
default to true by setting `spice.log.all`,
and make documentation updates to ensure that all configuration options
are documented.

log: Make --all configurable

---

doc/includes/cli-reference.md
dumpmd.go

For each command, enumerate configuration keys that affect it,
and link to the configuration reference.
This will be especially handy for config-only options
that don't have corresponding public flags.

doc: Enumerate configurations under each command

---

.changes/unreleased/Added-20240807-075520.yaml
doc/includes/cli-reference.md
doc/src/cli/config.md
doc/src/setup/auth.md
internal/forge/github/forge.go

Setting GITHUB_URL and GITHUB_API_URL environment variables
can be inconvenient.
Allow setting these values via git config if desired.

Support setting GitHub URLs via configuration

---

.changes/unreleased/Added-20240806-211807.yaml
branch_submit.go
doc/includes/cli-reference.md
doc/src/cli/config.md
doc/src/guide/pr.md
downstack_submit.go
internal/git/config.go
internal/git/config_test.go
internal/spice/config.go
stack_submit.go
submit.go
submit_test.go
testdata/script/branch_submit_navigation_comment_opt_out_multiple.txt
upstack_submit.go

Allow opting out of navigation comments in change requests,
or only posting them when there are multiple change requests.
This option may be set with the `--nav-comment` flag,
or the `spice.submit.navigationComment` configuration key.
Resolves #289

submit: Support navigation comment opt-out

---

branch_submit.go

This will play better with shell completion.

submit: Use enum for --nav-comment flag

---

doc/src/cli/shorthand.md
internal/cli/shorthand/expand.go
internal/cli/shorthand/expand_test.go

Instead of stopping expansion at the first match,
continue to expand the first argument of the result.
This allows user-defined shorthands to refer to built-in shorthands.

shorthands: Support cooperation b/w custom and built-in

---

.changes/unreleased/Changed-20240808-210829.yaml
doc/src/cli/config.md
doc/src/setup/auth.md
internal/forge/github/forge.go
internal/forge/github/forge_test.go

For GHES, usually the API URL is /api under the base URL.
So if the API URL is not set, and base URL is not github.com,
we can assume the API URL is $baseURL/api.
Users can still override this with the `spice.forge.github.apiUrl`
or `GITHUB_API_URL` environment variable.
Follow up to https://github.com/abhinav/git-spice/pull/330#issuecomment-2277077683
Relates to #336

forge/github: Determine API URL from base URL if not set

---

.changes/unreleased/Added-20240810-100319.yaml
branch_checkout.go
doc/includes/cli-reference.md
doc/src/cli/config.md
testdata/script/branch_checkout_prompt.txt

gs bco provides an --untracked flag that will show untracked branches
in the branch checkout flag.
Add a configuration option to make this the default behavior.

branch checkout: Add config analog for --untracked

---

auth.go
internal/cli/shorthand/builtin.go
internal/cli/shorthand/builtin_test.go
internal/forge/forge.go
internal/forge/forge_test.go
main.go
shell_completion.go

forge.All already matches the iter.Seq signature.
Use `range` to iterate over forge.All.

chore: Use range for forge.All

---

.github/workflows/doc.yml

Issues like b7a9571626f0df2083a237174271b74846e1f28e will be caught
before merging if we also attempt to build docs for PRs.
Just don't deploy them until they're merged.

ci: Run doc on PRs, just don't deploy them

---

dumpmd.go

Changing to maps.Keys, we lost the sorted order of the keys.

fix(doc): Shorthand list must be sorted

---

.changes/unreleased/Changed-20240816-054428.yaml
branch_onto.go
testdata/script/branch_onto.txt
testdata/script/branch_onto_diverged_from_base.txt
testdata/script/branch_onto_extract.txt
testdata/script/upstack_onto_diverged_from_base.txt
upstack_onto.go

The onto operations do two things:
- update internal state of the branch to target a new base
- rebase commits $oldBase..$branch onto $newBase
There's an expectation from users that if branch is already on target,
the command should still rebase the commits if the target is ahead of
the branch.
This change makes the onto operations always run,
even if the branch is already on target.
Resolves #321

onto: Apply even if branch is already on target

---

branch_submit.go
downstack_submit.go
stack_submit.go
submit.go
upstack_submit.go

Instead of submitSession just being a value-holder,
teach it how to fetch the remote and remote repository,
and use that everywhere.
memoizedValue now more closely matches its name.

refac(submitSession): Learn to fetch remote and remote repo

---

.changes/unreleased/Fixed-20240821-082941.yaml
branch_submit.go
downstack_submit.go
internal/forge/shamhub/forge.go
stack_submit.go
submit.go
testdata/script/issue351_submit_no_publish_unsupported_forge.txt
upstack_submit.go

If using `submit` commands with --no-publish,
there's no need to require remote repository information.
As long as we can `git push` to it, we're good.
This commit reorganizes the information retrieval in submit
commands to only fetch the remote repository information
when necessary.
Resolves #351

submit: --no-publish should work for unsupported forges

---

.changes/unreleased/Added-20240821-213515.yaml
branch_submit.go
doc/includes/cli-reference.md
doc/src/cli/config.md
testdata/script/branch_submit_config_no_publish.txt
upstack_submit.go

Change --no-publish to --publish, defaulting to true,
with a --no-publish opt-out.
Support setting the default value via configuration,
allowing users to always opt out of creating CRs,
unless the --publish flag is added to the command.
This will make the experience of using submit with unsupported forges
smoother.

submit: support --publish opt-in mode

---

branch_submit.go
doc/src/guide/pr.md
downstack_submit.go
internal/forge/forge.go
internal/forge/github/change_meta.go
internal/forge/shamhub/change_meta.go
stack_submit.go
submit.go
submit_test.go
upstack_submit.go

The in-code terminology does not match the user-facing terminology.
Update code references to 'stack comments' to 'navigation comments'
or 'stack navigation comments'.

refac: rename stack comment to navigation comment

---

.github/workflows/doc.yml
doc/mkdocs.yml

The privacy plugin downloads external resources (like fonts).
This is not necessary for PRs as these builds are not published.

doc: Don't download external resources for PRs

---

.changes/unreleased/Added-20240824-115459.yaml
branch_submit.go
doc/src/guide/pr.md
internal/forge/forge.go
internal/forge/github/comment.go
internal/forge/github/comment_test.go
internal/forge/github/integration_test.go
internal/forge/github/testdata/TestIntegration_Repository_ListChangeComments_paginated/comments
internal/forge/github/testdata/fixtures/TestIntegration_Repository_ListChangeComments_paginated.yaml
internal/forge/github/testdata/fixtures/TestIntegration_Repository_ListChangeComments_simple.yaml
internal/forge/shamhub/comment.go
submit.go
submit_test.go
testdata/script/branch_submit_by_name.txt
testdata/script/branch_submit_detect_existing.txt
testdata/script/branch_submit_navigation_comment_opt_out_multiple.txt
testdata/script/branch_submit_rename.txt
testdata/script/downstack_submit.txt
testdata/script/stack_submit.txt
testdata/script/stack_submit_update_leave_draft.txt
testdata/script/upstack_submit_main.txt

When importing CRs not currently known to git-spice,
detect any stack navigation comments on the CR and import them as well.
To reduce risk of hijacking unknown comments,
the comments must have both the following pieces:
- "This change is part of the following stack:"
- ``
The latter is new and placed at the bottom of stack navigation comments
starting this version.
If both pieces are present, and we have permission to edit that comment,
the comment is imported into the data store and updated as needed.
Resolves #325

submit: detect navigation comment in imported CRs

---

.goreleaser.yml

Before:
```
snapshot:
name_template: 'foo'
```
After:
```
snapshot:
version_template: 'foo'
```
Ref: https://goreleaser.com/deprecations/#snapshotname_template

goreleaser: snapshot.name_template is deprecated

---

.changes/unreleased/Fixed-20240829-202317.yaml
branch_submit.go
internal/spice/template.go
testdata/script/issue369_branch_submit_pr_template_cache_remote_update.txt

We calculate the template cache key based on the hashes of the files
inside the locations in the repository where tempates are stored,
but we check their state at `$trunk` instead of `$remote/$trunk`.
This results in the cache not being invalidated
if the remote has been updated and fetched, but the local ref is behind.
Ref #369

submit: Invalidate template cache if origin/main is updated

---

go.mod
go.sum
internal/termtest/with_term.go

v2 is in preview; the tag was deleted and there is no v2 branch.
The latest release is v1.1.23.

creack/pty: v2 -> v1

---

.changes/unreleased/Fixed-20240912-051752.yaml
internal/forge/shamhub/cli.go
internal/forge/shamhub/merge.go
repo_sync.go
testdata/script/repo_sync_merged_pr.txt
testdata/script/repo_sync_remote_already_deleted.txt

Right now, if you run `git pull` or `git fetch` with `--prune`
before calling `repo sync`,
it will complain that the remote tracking branch is missing.
It's only an error, not a warning, but it can still be confusing.
This makes `repo sync` check if the remote tracking branch exists
before trying to delete it,
making it a no-op if the branch has already been deleted.

repo sync: Don't complain about deleted remote branches

---

internal/forge/forge.go
internal/forge/github/integration_test.go
internal/forge/github/merged.go
internal/forge/github/testdata/fixtures/TestIntegration_Repository_ChangesAreMerged.yaml
internal/forge/shamhub/merge.go
repo_sync.go

Replace ChangeIsMerged with a bulk ChangesAreMerged API
that takes a list of ChangeIDs and returns a list of booleans
in the same order.
With this in place, we can change 'repo sync'
to make a single request for all submitted branches
instead of one request per branch.
[skip changelog]: No user facing changes in this branch.

forge: ChangeIsMerged -> ChangesAreMerged

---

.changes/unreleased/Changed-20240913-185002.yaml
repo_sync.go

Make use of the ChangesAreMerged to make a single network request
for all submitted branches, rather than one per branch.
We still need to make one request per tracked branch for now.

repo sync: Use ChangesAreMerged to batch check submitted branches

---

.changes/unreleased/Fixed-20240914-120358.yaml
repo_sync.go
testdata/script/repo_sync_after_merging_renamed_branch.txt

If a branch is renamed after submission and then merged,
the tracking branch name does not match the local branch name.
This case must be correctly handled when deleting the tracking branch:
if we know the upstream branch name use `$remote/$upstreamBranch`
instead of `$remote/$branch`.
Also drop the outdated comment about how we detect merged branches
sinc we're indeed doing both (1) and (2) now.

repo sync: Fix deleting wrong tracking branch for renamed branches

---

.changes/unreleased/Changed-20240914-175829.yaml
remote.go
repo_sync.go
testdata/script/issue391_repo_sync_pull_unsupported_forge.txt

When `repo sync` is run on a repository with a remote
that is not a known forge (e.g. GitLab),
instead of failing with an error because we can't detect merged PRs,
just log a warning and skip the branch deletion step.
This is only a partial fix for #391.
It'll still leave the merged branches around,
and worse, the upstack branches will still point to merged branches
as their bases.
Since we can easily detect merged branches that used a merge commit,
we will do that instead of a warning in a follow-up PR.

repo sync: Gracefully handle unsupported forges

---

.changes/unreleased/Changed-20240914-175829.yaml
doc/src/faq.md
doc/src/guide/pr.md
doc/src/recipes.md
remote.go
repo_sync.go
testdata/script/issue391_repo_sync_pull_unsupported_forge.txt

Follow up to #404.
Previously, we just skipped branch deletion for unknown forges.
This degrades more gracefully by doing a best-effort check
for merged branches by looking at what's reachable from the trunk.
This will not handle squashes or rebases,
but it's good enough in lieu of official support for the forge.
Resolves #391

repo sync: Delete merged branches for unknown forges

---

.github/workflows/ci.yml
.github/workflows/doc.yml
.github/workflows/publish-release.yml

using go-version-file would ease the go version management, which takes go.mod as source of truth.

ci: update to use `go-version-file` rather than `go-version`

---

doc/includes/cli-reference.md
repo_init.go

#419 made the behavior for re-initializing a repository more explicit,
especially with regards to handling branches stacked on the trunk.
We no longer leave them pointing to the old untracked trunk,
but update them to point to the new trunk.
This updates the `repo init --help` output to reflect this change.

repo init: Update --help per recent changes

---

.gitattributes
internal/spice/state/branch.go
internal/spice/state/branch_test.go
internal/spice/state/store_test.go
internal/spice/state/testdata/rapid/TestBranchStateUncorruptible/TestBranchStateUncorruptible-20240924203849-74162.fail
internal/spice/state/testdata/rapid/TestBranchStateUncorruptible/TestBranchStateUncorruptible-20240924204020-75460.fail
internal/spice/state/testdata/rapid/TestBranchStateUncorruptible/TestBranchStateUncorruptible-20240927055400-19887.fail

Instead of building and discarding the branch graph for UpdateBranch,
provide a BranchTx API to prepare changes to the branch state.
Required state will be loaded lazily as needed for the underlying checks.
Changes will be accumulated in the BranchTx until Commit is called.
For now, the old UpdateBranch method just wraps BranchTx.
We'll delete it in the future and use BranchTx directly everywhere.
[skip changelog]: No user facing changes.J ust a better version of #419.

state: Lazy branch graph load, incremental changes

---

.changes/unreleased/Fixed-20240927-074731.yaml
branch_create.go
testdata/script/branch_create_over_untracked.txt

By using the new BranchTx API,
we're able to check whether the store will accept the change
before we actually create the branch.
So, we now first prepare the transaction with the new branch state,
and only if that succeeds do we actually create the branch.
This way, if the store would reject the change
because the base branch is untracked or something similar,
we'll roll back to the original target branch and staged changes.

branch create: Don't create or commit if store would reject

---

.changes/unreleased/Fixed-20240928-110233.yaml
internal/forge/github/forge.go
internal/forge/github/forge_test.go

ssh://git@ssh.github.com:443/foo/bar.git is a valid GitHub URL.
Add handling for this: strip the port if it's a default port
*and* the base URL doesn't specify a port.
Resolves #425

forge/github: Recognize ssh://git@ssh.github.com:443 URLs

---

.changes/unreleased/Changed-20240928-162434.yaml
.changes/unreleased/Fixed-20240928-162724.yaml
.changes/unreleased/Fixed-20240928-162826.yaml
branch.go
branch_delete.go
doc/includes/cli-reference.md
internal/spice/branch.go
repo_sync.go
testdata/script/issue398_repo_sync_many_merged.txt

Previously, `repo sync` would invoke `branch delete`
for each merged branch in an indeterminate order,
which would first move the upstacks of that branch to its base,
then delete the branch.
When multiple branches are merged, this has issues:
- repeated work of constantly moving the same branches
- log noise
- in some corner cases, (e.g. #398), the order of deletion matters
and it causes the command to fail
The fix for this is multi-fold:
- `branch delete`: now accepts multiple branches
instead of just one branch.
- `branch delete`: delete branches in reverse topological order.
This will ensure that branches that have no dependents are deleted
before branches that depend on them.
- `branch delete`: when multiple branches are being deleted,
redirect the base of the upstacks to the next …

repo sync: Handle many merged, branch delete: support multiple

---

.github/workflows/bump-homebrew-formula.yml

git-spice is now in homebrew-core,
so update it automatically on release.

ci: On release, bump Homebrew formula

---

.changes/unreleased/Fixed-20241002-052319.yaml
branch_submit.go
testdata/script/stack_submit_update_leave_draft.txt

cmd.Draft is a pointer, so "set draft to"
was printing a memory address instead of true/false.
Resolves #433

branch submit: Fix draft status --dry-run log

---

.changes/unreleased/Fixed-20241025-231804.yaml
internal/forge/github/comment.go
internal/forge/github/comment_test.go

This PR fixes a bug in the loop where we always select the first comment and don't filter anything due to a misplaced `continue`.
fixes #447

fix: correct navigation comment selection

---

.changes/unreleased/Added-20241019-110354.yaml
.changes/unreleased/Added-20241019-110430.yaml
bottom.go
branch_checkout.go
doc/includes/cli-reference.md
down.go
testdata/script/nav_detach_dry_run.txt
top.go
trunk.go
up.go

All commands that check out branches (up, down, top, bottom, trunk, bco)
now support -n/--dry-run to print the target branch,
and --detach to check that branch out in a detached HEAD state.

navigation commands: -n/--dry-run and --detach

---

.changes/unreleased/Added-20241026-102334.yaml
branch_submit.go
doc/includes/cli-reference.md
doc/src/cli/config.md
go.mod
go.sum
internal/browser/browser.go
internal/browser/browser_test.go
internal/browser/browsertest/recorder.go
internal/browser/browsertest/recorder_test.go
main.go
script_test.go
testdata/script/branch_submit_web.txt
testdata/script/branch_submit_web_opt_out.txt
testdata/script/stack_submit_web.txt

If set, the `gs branch submit` and related commands
will open a web browser with the submitted CR.
This can be made the default by setting `spice.submit.web` to `true`.
Resolves #446

submit: Add -w/--web flag to open a browser

---

.changes/unreleased/Fixed-20241102-094426.yaml
branch_submit.go
testdata/script/branch_submit_rename_base.txt

When submitting a branch, we already handle the case
where the local branch has been renamed since submitting.
The original upstream name is still used.
But we did not account for that change
when submitting branches based on top of the renamed branch.
This fixes that--just a matter of plumbing the right variables around.

fix(branch submit): handle base branch renaming

---

.changes/unreleased/Fixed-20241106-052308.yaml
.changes/unreleased/Fixed-20241108-054719.yaml
.changes/unreleased/Fixed-20241108-055122.yaml
branch_submit.go
internal/git/remote.go
internal/git/remote_test.go
internal/spice/mock_service_test.go
internal/spice/remote.go
internal/spice/remote_test.go
internal/spice/service.go
internal/spice/service_test.go
testdata/script/branch_submit_detect_existing_conflict.txt
testdata/script/branch_submit_detect_existing_upstream_name.txt
testdata/script/branch_submit_many_upstream_names_taken.txt
testdata/script/branch_submit_upstream_name.txt
testdata/script/branch_submit_upstream_name_wrong_remote.txt

When submitting a branch `$name`,
it's possible that someone else has already taken that name.
For example, the local branch name might be something generic
like 'feature', and someone else may already have taken that name.
To handle this case, gs will now query the remote with `git ls-remote`,
and generate a unique name for the branch if the original name is taken.
New names start at `$name-2`, and keep incrementing the number
until a free name is found.
Making this change results in a couple other changes:
- If the branch has an upstream associated with it,
e.g. with `git push -u origin foo:bar`, we'll prefer that name
since the user has already pushed the branch and chosen it.
This makes sense: I pushed the branch, and associated the upstream
with the branch, so that's what should be …

submit: Generate unique remote name if branch name is taken

---

.changes/unreleased/Added-20241109-095515.yaml
branch_submit.go
branch_submit_test.go
doc/includes/cli-reference.md
doc/src/cli/config.md

The hard-coded timeout for looking up CR templates
was causing issues for users with slow connections.
```
WRN Could not list change templates error="list templates: Post \"https://api.github.com/graphql\": context deadline exceeded"
```
This adds a `spice.submit.listTemplatesTimeout` configuration
to configure this timeout.
Setting the timeout to 0 disables it completely.
Resolves #438

submit: list templates: allow configuring timeout

---

.changes/unreleased/Changed-20241102-095155.yaml
branch_split.go
branch_submit.go
doc/includes/captures/README.txt
doc/includes/captures/branch-split-reassociate.txt
doc/src/guide/branch.md
internal/git/branch.go
internal/git/branch_test.go
internal/spice/branch.go
internal/spice/state/branch.go
internal/spice/state/branch_test.go
internal/spice/state/store_test.go
internal/ui/form.go
main.go
testdata/script/branch_split_reassign_submitted.txt

When splitting a branch that has already been submitted,
prompt the user to reassign the CR to one of the branches
(defaulting to the original branch).
Resolves #410

branch split: prompt for CR reassignment

---

branch_submit.go

Don't open the browser when --dry-run is used
even if --web is specified.
[skip changelog]: not yet released

fix(branch submit): ignore --web in --dry-run mode

---

.changes/unreleased/Fixed-20241111-182144.yaml
main.go

If the command is renamed, don't use "gs" as the name in help
or in the completion script. Use the renamed command name instead.
e.g.
```
❯ make bin/gs
❯ mv bin/gs gsp
❯ ./gsp shell completion bash
complete -C /.../src/git-spice/gsp gsp
```
Refs #469

completion: recognize renamed binary

---

.changes/unreleased/Added-20241123-225228.yaml
repo_sync.go
testdata/script/repo_sync_restack.txt

This change adds a --restack flag to `repo sync` which allows users to automatically restack their active stack after syncing the repo.
Fixes https://github.com/abhinav/git-spice/issues/384
---- 
Hi! Thanks for the useful tool. Also thanks for marking the issue as suitable for a first-time contributor. I hope the change is good, happy to take any feedback here!
I'm one of the maintainers of https://github.com/pulumi/pulumi-terraform-bridge and have recently started using git-spice and have found it very useful. See for example this currently active stack for an example of my usage: https://github.com/pulumi/pulumi-terraform-bridge/pull/2629 - It currently has 5 active PRs and 6 have already been merged.
I'm also interested in https://github.com/abhinav/git-spice/issues/314 and …

Add a --restack flag to repo sync

---

CONTRIBUTING.md

It was missing gofumpt and golangci-lint (this came up in #477).
Also mention some more styling guidance.

CONTRIBUTING: Add more guidelines

---

internal/forge/gitlab/auth.go

Verified that it still works with just this.
[skip changelog]: feature not yet released

gitlab: Reduce OAuth scope to just "api"

---

.github/workflows/ci.yml

Coverage output sometimes messes up Windows integration tests.
Run without coverage on Windows for now.
In the future, we can split out unit and integration tests,
and run coverage only on the unit tests.
[skip changelog]: not user facing

ci/windows: run without coverage

---

.changes/unreleased/Added-20241125-222348.yaml
doc/includes/cli-reference.md
doc/src/cli/config.md
internal/forge/gitlab/auth.go
internal/forge/gitlab/forge.go

his pull request introduces a new configuration option for specifying the OAuth Client ID when using GitLab as the forge. This allows users to configure the client ID for their GitLab Self Managed instance, enabling proper OAuth authentication.

feat: Add OAuth Client ID configuration option for GitLab forge

---

.changes/unreleased/Added-20241127-125953.yaml
commit_create.go
doc/includes/cli-reference.md
internal/git/commit.go
testdata/script/commit_create_fixup.txt

This adds a new --fixup flag for allowing you to create fixup commits.
--fixup takes a commitish which targets where the fixup will be applied.
--fixup also takes the search :/<text> to target the subject of a commit
message to target the correct commit.
Using gs branch edit with the autosquash option set in git allows us to
automatically fixup our commits.
Resolves #492

commit create: Add --fixup flag

---

.changes/unreleased/Changed-20241129-120946.yaml
commit_amend.go
doc/includes/cli-reference.md
testdata/script/branch_submit_config_no_publish.txt
testdata/script/commit_amend_deprecated_short_form.txt
testdata/script/commit_amend_rebase.txt

`git commit --no-edit` does not have a `-n` short form
so we shouldn't either.
In the interest of not breaking anyone, just deprecate the flag first.
We'll warn users when they use the short form for now.
Refs https://github.com/abhinav/git-spice/issues/380#issuecomment-2508558831

commit amend: deprecate -n in favor of --no-edit

---

.changes/unreleased/Added-20241130-172501.yaml
doc/includes/cli-reference.md
doc/src/cli/config.md
internal/git/repo.go
internal/git/repo_test.go
rebase_continue.go
testdata/script/branch_restack_conflict_no_edit.txt

Git's `rebase --continue` always opens an editor
to edit the commit message after resoling the conflict.
There are cases where this is not necessary.
This adds a `--no-edit` flag to `gs rebase continue`
to skip opening an editor.
`rebase` does not have a `--no-edit` flag to skip the editor
but we can get the same effect by setting the editor to `true`
for that command.
Resolves #503

rebase continue: Add --no-edit flag to skip opening an editor

---

.changes/unreleased/Added-20241201-115758.yaml
branch_create.go
commit_amend.go
commit_create.go
commit_split.go
doc/includes/cli-reference.md
internal/git/commit.go
testdata/script/branch_create_no_verify.txt
testdata/script/commit_amend_no_verify.txt
testdata/script/commit_create_no_verify.txt
testdata/script/commit_split_no_verify.txt

Adds the --no-verify flag to allow the user to bypass the pre-commit and commit-msg hooks for all actions that create a commit.
This is useful for allowing the user to skip these hooks for a single commit action and keep the automatic restack functionality.
Resolves #380

commit {create, amend, split}branch create: Adds --no-verify flag

---

internal/git/tree.go
internal/git/tree_test.go

When all files from a tree are deleted,
delete the subtree from the parent tree
instead of leaving an empty entry behind.
This matches git's behavior.

git/UpdateTree: Don't leave empty trees behind

---

.changes/unreleased/Changed-20241220-091825.yaml
branch_delete.go
internal/graph/doc.go
internal/graph/topo.go
internal/graph/topo_test.go

Extract the topological sort logic used in branch_delete
into a separate package so that we can reuse it in #508.
A small user-facing change of this is that 'branch delete'
will delete branches in a more deterministic order.

internal: Generalize topological sort

---

internal/forge/forge.go
internal/forge/forgetest/mocks.go
internal/forge/github/change_meta.go
internal/forge/github/change_meta_test.go
internal/forge/gitlab/change_meta.go
internal/forge/gitlab/change_meta_test.go
internal/forge/shamhub/change_meta.go

Add a means for forges to serialize and deserialize just their ChangeIDs
without any other change metadata.
This will be used by #508.

forge: Add MarshalChangeID/UnmarshalChangeID

---

.changes/unreleased/Added-20241220-211843.yaml
branch_submit.go
doc/includes/cli-reference.md
doc/src/guide/cr.md
testdata/script/submit_update_only.txt

For all submit commands, add an `--update-only` flag
that will update existing open CRs but not create new ones.
Resolves #516

submit: Add --update-only flag

---

internal/forge/shamhub/merge.go
repo_sync.go

When bubbling up downstack history,
don't nuke the history of a merged branch until it's deleted.
If this branch fails to be deleted/untracked for any reason,
we'll still have this history to work with.

repo sync/downstack history: Don't nuke merged branch history

---

internal/forge/shamhub/merge.go
repo_sync.go
testdata/script/repo_sync_unsubmitted_upstack_history.txt

Add a test for how merge history propagation behaves
for upstack branches that are unsubmitted.
Suppose I have `feat1 -> feat2`:
- feat1 is ready and I submit a CR
- feat2 is not yet ready for review, so it is unsubmitted
- while I'm still working on feat2, feat1 gets approved and I merge it
- I then submit feat2
feat2 still shows feat1 in its downstack history.
We can change this behavior in the future if it makes sense
but right now I lean towards more information over less.

repo sync: don't propagate downstack history for unsubmitted branches

---

.changes/unreleased/Added-20250103-052535.yaml
.goreleaser.yml

Sets up the Homebrew tap to also install shell completions
generated from the `gs` executable.

releaser/tap: Install completions

---

internal/git/gittest/config.go
testdata/script/branch_submit_no_publish.txt
testdata/script/issue391_repo_sync_pull_unsupported_forge.txt
testdata/script/repo_sync_merged_pr.txt
testdata/script/repo_sync_remote_already_deleted.txt

Looks like `git log --graph --decorate` now includes origin/HEAD
in the output in newer versions.
Rather than try to make the output match different versions,
freeze some of the bits, e.g. never list origin/HEAD.

tests: Handle Git output changes

---

internal/forge/stacknav/nav.go
internal/forge/stacknav/nav_test.go
submit.go

Add a new forge/stacknav package that renders stack navigation comments
as a Markdown list.

refac(submit): extract stack navigation rendering

---

.changes/unreleased/Added-20250202-192729.yaml
branch.go
branch_checkout.go
branch_squash.go
doc/includes/cli-reference.md
doc/includes/cli-shorthands.md
internal/git/branch.go
internal/git/commit.go
testdata/script/branch_squash.txt
testdata/script/branch_squash_err.txt
testdata/script/branch_squash_message.txt

Resolves #558, using the procedure discussed, namely
1. Verifies that the current branch can be squashed
1. Checks out the current branch in a detached state
2. Resets the detached branch to the base branch
3. Commits all staged changes, using either the original first commit msg, or a provided message
4. Updates the HEAD ref of the current branch to the hash that was created in the previous step
5. Checks out the current branch

feat(branch): add `gs branch squash`

---

.github/workflows/prepare-release.yml
branch.go
doc/includes/cli-reference.md
dumpmd.go

For new commands, report which version they were released in
(if at all).

doc: Add 'unreleased' support to CLI commands

---

branch_submit_test.go
go.mod
internal/forge/github/auth_test.go
internal/forge/github/comment_test.go
internal/forge/github/integration_test.go
internal/forge/gitlab/auth_test.go
internal/forge/gitlab/comment_test.go
internal/forge/gitlab/integration_test.go
internal/git/branch_test.go
internal/git/config_test.go
internal/git/integration_test.go
internal/git/pull_test.go
internal/git/rebase_test.go
internal/git/remote_test.go
internal/git/tree_test.go
internal/spice/branch_test.go
internal/spice/config_test.go
internal/spice/remote_test.go
internal/spice/state/branch_test.go
internal/spice/state/storage/backend_test.go
internal/spice/state/storage/git_test.go
internal/spice/state/store_test.go
internal/spice/state/version_test.go
internal/spice/template_test.go

t.Context was added in Go 1.24 to provide a context
that is valid only for the lifetime of a test function.
This change updates test functions to use this context where possible.
Cases where it can't be used:
- rapid tests
- t.Cleanup functions

all(test): prefer t.Context where possible

---

.golangci.yml
internal/fixturetest/fixturetest_test.go
internal/forge/github/integration_test.go
internal/forge/gitlab/integration_test.go
mise.lock

This commit enables the `usetesting` linter in the golangci.yml file
and fixes issues found by it.

ci(lint): enable usetesting

---

.github/workflows/changelog-merge.yml
.github/workflows/prepare-release.yml
mise.toml
tools/ci/prepare-release/main.go

Turn the work done by the prepare-release.yml workflow
into a single Go program/script that does the work.
Relying on sed was starting to feel brittle.
Testing:
Ran the workflow manually: https://github.com/abhinav/git-spice/actions/runs/13428957214

ci: Turn prepare-release workflow into a script

---

.changes/unreleased/Fixed-20250221-092625.yaml
internal/git/cmd.go
internal/git/cmd_test.go
internal/git/config.go
internal/git/config_test.go
internal/git/rebase.go
internal/git/remote.go
internal/git/repo.go
internal/git/var.go

As we were injecting configurations into git commands at runtime,
log prefixes for affected commands were just `-c`.
To fix this, make newGitCmd aware of extraConfig
so it can guess at a command name while ignoring the `-c` flags,
and add the ability to change the log prefix,
as that's required for rebase command when --no-edit is enabled.

fix(git): show command name in log prefix

---

.changes/unreleased/Fixed-20250221-120939.yaml
upstack_onto.go

When upstack onto presents a prompt to select the new base,
it should not allow selecting the current branch or any of its upstacks
as that operation will fail.

fix(upstack onto): disable upstack branches in prompt

---

main.go

BindToProvider in Kong will create new instances of bindings
that come from a provider function every time they're requested
by another binding.
This means that we always re-open some of these resources
multiple times: e.g. repository is opened when requested by state.Store,
by spice.Service, and then by individual commands.
Work around this with a sync.Once until the new
[BindSingletonProvider option](https://github.com/alecthomas/kong/pull/501)
is released.

chore(kong): BindToProvider singletons workaround

---

.changes/unreleased/Changed-20250222-094533.yaml
branch.go
testdata/script/branch_checkout_prompt.txt
testdata/script/branch_checkout_prompt_sort_by_committerdate.txt
testdata/script/branch_delete_prompt_untracked.txt

We currently list untracked branches as root nodes
when presenting the branch selection tree.
This doesn't seem right: untracked branches are still based off of trunk
(unless they have completely divergent histories,
which we won't account for -- at least for now).
Present untracked branches as being based on trunk.
Resolves #443

branch prompt: Untracked branches are based on trunk

---

.changes/unreleased/Fixed-20250222-113654.yaml
branch_rename.go

Support tab completions on the old branch name
when using `gs branch rename <old> <new>` form.

fix(branch rename): tab-complete old branch name

---

.changes/unreleased/Changed-20250222-094533.yaml
branch.go
testdata/script/branch_checkout_prompt.txt
testdata/script/branch_checkout_prompt_sort_order.txt
testdata/script/branch_delete_prompt_sort_order.txt
testdata/script/branch_delete_prompt_untracked.txt

Putting untracked branches under main takes away knowledge
that they are untracked in the branch selection prompt.

(revert #590) branch select: untracked branches are on their own

---

.goreleaser.yml

This should now be archives.formats.
https://goreleaser.com/deprecations/#archivesformat

goreleaser: archives.format deprecated

---

version.go

Rather than try to keep year up-to-date or generate on demand,
just drop the year. That's also considered okay.
https://daniel.haxx.se/blog/2023/01/08/copyright-without-years/
[skip changelog]: not really user-facing

--version copyright: drop year

---

.changes/unreleased/Added-20250224-083159.yaml
doc/includes/cli-reference.md
main.go
version.go
version_test.go

Adds a version subcommand to report version information
instead of/in addition to the --version flag.
In service to #572

Add version command

---

doc/includes/cli-reference.md
version.go
version_test.go

Per discussion in #572, add a --short flag to the version command
to print only the version number.
[skip changelog]: version command is unreleased,
this is just an addition to that.
Resolves #572

version: --short flag to print only the version

---

internal/spice/branch.go
internal/spice/branch_test.go
internal/spice/remote_test.go
internal/spice/service.go
internal/spice/service_test.go
internal/spice/template_test.go
main.go

Service doesn't need to know Forge (at least at this time)
as all logic is implemented outside it.

internal/spice: Drop Forge from Service

---

auth.go
internal/forge/forge.go
internal/forge/forge_test.go
remote.go

Move the logic from the global forge registry into a Registry type
that mirrors the APIs (more or less).
In this change, we still have a global registry;
following this we can drop the global registry.

refac(forge): extract global registry into type

---

auth.go
branch_split.go
branch_submit.go
downstack_submit.go
internal/forge/forge.go
internal/spice/branch.go
internal/spice/branch_test.go
internal/spice/remote_test.go
internal/spice/service.go
internal/spice/service_test.go
internal/spice/template_test.go
main.go
remote.go
repo_sync.go
script_test.go
shell_completion.go
stack_submit.go
submit.go
upstack_submit.go

Replace the global forge registry with
an explicitly plumbed Registry object.

refac(forge): Drop global registry

---

.changes/unreleased/Fixed-20250305-215537.yaml
internal/forge/gitlab/client.go
internal/forge/gitlab/client_int_test.go
internal/forge/gitlab/integration_test.go

The GitLab forge was rejecting use of the GITLAB_TOKEN env var
for authentication despite advertising support for it.
The issue was that the client constructor was exploding
when the auth type was `AuthTypeEnvironmentVariable`
because it was not in the list of known auth types.
Fix this by adding a case for it, and add tests to verify.
Resolves #612

fix(gitlab): Actually support GITLAB_TOKEN

---

internal/forge/forge.go
internal/forge/forgetest/mocks.go
internal/forge/github/forge.go
internal/forge/github/forge_test.go
internal/forge/gitlab/forge.go
internal/forge/gitlab/forge_test.go
internal/forge/shamhub/forge.go
internal/forge/shamhub/repo.go

Needed for #610, #615
We currently don't expose a standard way to determine the URL
at which a CR can be viewed in a forge-agnostic way.
This adds a ChangeURL method to Forge that can be used for this purpose.
The method is a bit of a hack as this information should typically
come from the Repository, except right now,
we do not have a means of narrowing down to a Repository
without "opening" it, which may perform network requests.
There's an in-flight change that separates the act of
parsing a repository URL and opening it,
which will allow making this cleaner in the future.

forge: Learn to calculate change URLs

---

.changes/unreleased/Added-20250316-082145.yaml
doc/src/cli/config.md
internal/git/commit.go
internal/git/commit_test.go
log.go
log_test.go
testdata/script/config_log_push_status_format.txt

Allow setting log.pushStatusFormat to aheadBehind,
which will report the number of commits a branch is ahead/behind
its upstream in the form `⇡1⇣2`.
This is similar to what is produced
by popular terminal prompt plugins for Git
(e.g. powerlevel10k, starship).
Examples:

feat(log.pushStatusFormat): support aheadBehind

---

branch.go
main.go

New Kong was released with #501, which introduces BindSingletonProvider.
This allows dropping the `onceFunc` workaround.

chore(cli): use kong.BindSingletonProvider

---

branch_checkout.go
internal/git/branch.go
internal/git/branch_test.go
repo_sync.go

For LocalBranches, instead of just reporting
whether a branch is checked out, also report _where_ it's checked out.
Step towards solving #126

git/LocalBranches: include Worktree in result

---

.changes/unreleased/Added-20250319-181541.yaml
internal/git/repo.go
repo_sync.go
testdata/script/repo_sync_trunk_checked_out_in_another_worktree.txt

If trunk is checked out in another worktree,
switch to operating on that worktree and update trunk there.
This is just a `git pull` or `git pull --rebase` in that directory.
Resolves #126

repo sync: update even if trunk is checked out

---

.changes/unreleased/Changed-20250405-111557.yaml
internal/spice/branch.go
log.go

Instead of fetching branch information serially,
fetch it with a bunch of parallel workers to speed up the process.
Results:
On my laptop, even with just 17 branches,
'gs ll -a' went from ~510ms to ~160ms.
```
❯ hyperfine --warmup 5 'gs ll -a'
Benchmark 1: gs ll -a
Time (mean ± σ):     515.4 ms ±   3.5 ms    [User: 282.2 ms, System: 215.3 ms]
Range (min … max):   511.1 ms … 522.5 ms    10 runs
❯ hyperfine --warmup 5 'gs ll -a'
Benchmark 1: gs ll -a
Time (mean ± σ):     160.9 ms ±   3.7 ms    [User: 404.6 ms, System: 475.9 ms]
Range (min … max):   156.7 ms … 172.3 ms    18 runs
```
I also created a repository with 100 branches with:
```bash
git init
git commit --allow-empty -m "init"
gs repo init
for num in {0..100}; do
gs trunk
echo "$num" > "file.$num.txt"
git add "file.$num.txt"
gs bc …
```

log {long, short}: fetch branch information in parallel

---

.github/actions/go-cache/action.yml
.github/workflows/autofix.yml
.github/workflows/ci.yml

Persist GOCACHE and GOMODCACHE between runs to make CI faster.

ci: cache GOCACHE and GOMODCACHE between runs

---

.github/actions/install-git/action.yml
.github/workflows/ci.yml

The main CI workflow is messy.
Clean it up a bit with a separate action to install Git.
[skip changelog]: No user facing changes

ci: Move Git installation to a separate action

---

mise.lock

Upgrade to Go 1.24.2

---

.github/workflows/ci.yml
mise.toml

PR #636 introduced parallel workers for log data collection.
We may add more parallelism in the future.
Race detection was previously disabled to keep test execution time
low back when it was sub 30 seconds.
With Windows tests, it takes 5 minutes anyway,
so there's no reason to keep it disabled for Linux.

ci: Run tests with race detection

---

main.go
mise.toml
profile_disable.go
profile_enable.go

'mr build --pprof` will generate a build
that will add three new flags: --cpuprofile, --memprofile, and --trace.
These can be used to generate profiles and debug performance issues.
These are not included by default to avoid bloating the binary size.

Support building with cpu, mem, and trace profiles

---

.changes/unreleased/Added-20250425-161027.yaml
commit_amend.go
commit_create.go
doc/includes/cli-reference.md
testdata/script/commit_amend_allow_empty.txt
testdata/script/commit_create_allow_empty.txt

This allows empty commits to be created and amended. Empty commits contain an message, but no changes to the repository.

commit {create, amend}: Adds --allow-empty flag

---

.changes/unreleased/Added-20250511-105903.yaml
branch_checkout.go
doc/includes/cli-reference.md
doc/src/cli/config.md
testdata/script/branch_checkout_track_prompt_opt_out.txt

When 'gs branch checkout' is used to checkout a branch
that is not tracked, git-spice presents a prompt to begin tracking it.
This can be annoying if you frequently open untracked branches.
This change adds a configuration option to opt out of the prompt.

bco: Allow disabling "do you want to track this branch" prompt

---

.changes/unreleased/Added-20250513-145103.yaml
branch_create.go
doc/includes/cli-reference.md
doc/src/cli/config.md
testdata/script/branch_create_prefix.txt

It'd be nice to be able to always add a prefix to the name of any branch that gets created.
Addresses https://github.com/abhinav/git-spice/issues/656

Add branch prefix option

---

.changes/unreleased/Fixed-20250517-164653.yaml
internal/spice/branch.go
internal/spice/branch_test.go
internal/spice/state/branch_int_test.go
internal/spice/state/branch_test.go
internal/spice/state/statetest/statetest.go
internal/spice/state/store_test.go
testdata/script/branch_submit_rename_and_delete_after_push.txt

If an upstream branch reference is deleted manually
(e.g. with git push --delete, or by deleting the remote branch),
then the state's local knowledge of the upstream branch name is stale
and should be deleted.
This does not solve, but helps with issues like #655,
as the user won't have to untrack the branch
to delete stale information.

state: detect upstream ref deletion

---

doc/includes/cli-reference.md
dumpmd.go

If a flag can be set with an environment variable,
mention that in the CLI reference.

doc/cliref: Include environment variables

---

.changes/unreleased/Added-20250521-144134.yaml
internal/ui/select.go
internal/ui/widget/branch_select.go

in addition to up and down arrows, to navigate selection lists where text input is allowed to refine the list of options, this adds ctrl+k and ctrl+j as alternatives, similar to other tools like fzf.
i didn't see existing tests for up/down to build off of, but i did manually test this locally and it behaves as expected.

feat: add ctrl+k and ctrl+j navigation keys for select uis

---

internal/log/attr.go
internal/log/attr_test.go
internal/log/handler.go
internal/log/handler_test.go
internal/log/level.go
internal/log/level_test.go
internal/log/log.go
internal/log/log_test.go
internal/log/logtest/logger.go
internal/log/logtest/logger_test.go
internal/log/style.go
internal/log/style_test.go
internal/log/writer.go
internal/log/writer_test.go

charmbracelet/log has gotten us pretty far,
but for the level of control I want going forward,
we need our own wrapper around slog.
This changes just adds the new logger implementation.
Following changes will switch to it.
logtest and log.Writer are copy-pasted from the versions in logutil.
[skip changelog]: This change contains no user facing changes yet.

Custom slog-based Logger

---

go.mod
internal/log/handler.go
internal/log/handler_slog_test.go
internal/log/handler_test.go
internal/log/log_test.go

Styling should not cross newline boundaries,
i.e. Render(line) should never have a newline in it.

fix(log): fix multiline message formatting

---

.changes/unreleased/Fixed-20250524-064820.yaml
internal/git/branch.go
internal/git/branch_test.go

'gs branch split' prompts the usre for a branch name,
and its validation function uses 'git rev-parse --verify'
to check if the planned branch name exists.
Without the '--quiet' flag, rev-parse logs errors to stderr,
which will get printed to the terminal in verbose mode.

branch split: Fix rev-parse logs while typing name

---

.changes/unreleased/Added-20250517-112151.yaml
.changes/unreleased/Changed-20250521-194858.yaml
doc/includes/cli-reference.md
internal/log/handler_test.go
internal/log/level.go
internal/log/level_test.go
internal/log/log.go
internal/log/log_test.go
internal/log/logtest/logger.go
internal/log/style.go
main.go

We'll stick with just debug logging for now.
Trace should be easy to add back later if needed.

log: Drop --verbosity flag and trace level

---

internal/log/handler.go
internal/log/log.go
internal/log/log_test.go
internal/log/style.go
internal/log/style_test.go

Add WithLevel and WithPrefix methods to the logger.
Versus SetLevel, WithLevel returns a new logger,
leaving old level unchanged.

feat(log): WithLevel and WithPrefix

---

branch_create.go
branch_delete.go

In cases where PeelToCommit is only used to check if a branch exists,
use BranchExists instead.

chore: use BranchExists instead of PeelToCommit

---

internal/log/style.go

[skip changelog]: not yet shipped, so no changelog entry needed

chore(log): don't bold all messages

---

branch_create.go
testdata/script/branch_create_prefix_with_generated_name.txt

When 'branch create' generates a branch name based on the commit,
if the branch name already exists, it appends a number to the name.
Right now, we add the prefix to the generated name afterwards,
which means that there's a chance that the final name
will conflict with an existing branch.
This change fixes this by ensuring that the prefix is taken into account
when generating the branch name.
[skip changelog]: change hasn't been released yet

fix(branch create): prefix in branch name conflict resolution

---

internal/silog/handler.go

Prefix shouldn't stand out from the message.
[skip changelog]: not yet released

log: style prefix same as message

---

internal/git/tree.go
internal/git/tree_test.go
internal/sliceutil/all.go
internal/sliceutil/empty.go
internal/spice/state/storage/git.go

Avoids allocating slices repeatedly.

refac(git/tree): use iterators for Make, List, etc.

---

.changes/unreleased/Fixed-20250531-093358.yaml
branch_submit.go
internal/forge/forge.go
internal/forge/github/integration_test.go
internal/forge/github/ref.go
internal/forge/github/submit.go
internal/forge/github/testdata/TestIntegration_Repository_SubmitChange_baseBranchDoesNotExist/base-branch
internal/forge/github/testdata/TestIntegration_Repository_SubmitChange_baseBranchDoesNotExist/branch
internal/forge/github/testdata/fixtures/TestIntegration_Repository_SubmitChange_baseBranchDoesNotExist.yaml
internal/forge/shamhub/ref.go
internal/forge/shamhub/submit.go
internal/graphqlutil/error.go
testdata/script/branch_submit_unsubmitted_base.txt

When GitHub rejects a PR because the base branch doesn't exist,
the error is super unhelpful:
```
FTL gs: create change:
create pull request: Post "https://api.github.com/graphql":
createPullRequest: UNPROCESSABLE:
Head sha can't be blank,
Base sha can't be blank,
No commits between he/feat1 and he/feat2,
Base ref must be a branch
```
(Newlines added for readability.)
To improve the UX around this, this change adds a check at submission:
if the request failed, and the base branch does not exist,
we return a more user-friendly error message.
Note that this error isn't returned for GitLab yet;
from experimentation, GitLab lets you submit an MR
even without the base branch being pushed,
and just reports the warning in the UI on the website.
Resolves #686, #460

branch submit: Better error when base hasn't been pushed

---

.changes/unreleased/Fixed-20250613-205329.yaml
.github/workflows/autofix.yml
internal/forge/gitlab/auth.go
internal/forge/gitlab/auth_test.go

New gitlab token has format `glab-AAAAA`. The current regex doesn't work.
Tested here
https://go.dev/play/p/akATgbSqGmW

Fix gitlab token regex

---

.changes/unreleased/Added-20250620-211723.yaml
.changes/unreleased/Added-20250622-211724.yaml
doc/includes/cli-reference.md
doc/mise.lock
doc/mise.toml
doc/src/cli/config.md
log.go
mise.lock
testdata/script/config_log_combined_change_format.txt
testdata/script/config_log_long_change_format.txt
testdata/script/config_log_short_change_format.txt

Adds the `gs ll` and `gs ls` specific overrides for crFormat
discussed in #693.
Resolves #693

config: add spice.{logShort, logLong}.crFormat options

---

.changes/unreleased/Fixed-20250621-093946.yaml
internal/git/files_wt.go
internal/git/files_wt_test.go
internal/git/rebase_wt.go
internal/git/rebase_wt_test.go
testdata/script/issue701_stack_edit_with_unstaged_changes.txt

'git rebase --autostash' exits with a zero exit code
even when the auto-stashed changes fail to apply,
and leaves the worktree in a conflicted state
(with merge-pending files).
This can result in multi-rebase operations
(`gs stack edit`, `gs upstack restack`, etc.)
trying to continue with the following rebases in a conflicted state,
also updating internal state to reflect the new branch order.
This implements an imperfect workaround to the problem:
detect if there are any unmerged files after the rebase,
and if so, fail the entire operation with an error message.
We should explore a more robust solution in the future,
but this will at least prevent the state from getting corrupted.
Resolves #701

git/rebase: detect autostash conflicts

---

.changes/unreleased/Added-20250621-143644.yaml
branch_submit.go
doc/includes/cli-reference.md
internal/git/push.go
internal/git/push_test.go
testdata/script/branch_submit_no_verify.txt

Adds a `--no-verify` flag similar to `gs commit create --no-verify`
that allows users to bypass pre-push hooks when submitting branches.
Resolves #635

submit: add --no-verify flag to bypass pre-push hooks

---

.changes/unreleased/Changed-20250622-143159.yaml
branch_create.go
internal/spice/branch.go
testdata/script/branch_create_over_untracked.txt

branch create rejects untracked base branches,
but only after the user has written a commit message.
This is a form of lost work, especially if the commit message is long.
This changes branch create to reject untracked base branches earlier,
so that the user does not have to write a commit message first.
Resolves #652

branch create: reject untracked base branch earlier

---

.changes/unreleased/Changed-20250622-152432.yaml
.changes/unreleased/Changed-20250622-165742.yaml
commit_amend.go
testdata/script/commit_amend_rebase_prompt.txt

If commit amend is called during a rebase operation
with unresolved conflicts, the user probably didn't want to do that.
Offer to abort the operation.
Resolves #700

commit amend: Detect rebase with unresolved conflicts

---

internal/git/wt.go
internal/git/wt_test.go

Add a means of listing all known worktrees for a repository
and their attributes.

git/Repository: Add Worktrees method

---

.changes/unreleased/Fixed-20250704-202339.yaml
.changes/unreleased/Fixed-20250704-202433.yaml
branch_delete.go
internal/git/wt.go
repo_sync.go
testdata/script/repo_sync_branch_in_another_wt_skip_deletion.txt
testdata/script/repo_sync_trunk_in_another_wt_current_branch_delete.txt

This changes 'repos sync' and 'branch delete' to handle two worktree
cases better:
- repo sync: if a branch slated for deletion is checked out
in another worktree, skip it
- branch delete: if the branch that would be checked out after
deletion is checked out in another worktree, detach HEAD
Resolves #665

{repo sync, branch delete}: handle worktrees better

---

.changes/unreleased/Added-20250704-204310.yaml
branch_submit.go
doc/includes/cli-reference.md
doc/src/cli/config.md
testdata/script/branch_submit_draft_config_interactive.txt
testdata/script/branch_submit_draft_config_noninteractive.txt

Add a spice.submit.draft configuration option
that will control the default value of --draft/--no-draft
when creating new CRs with `gs branch submit` and friends.
In interactive mode, this merely controls the default value
of the prompt that asks for the draft status.
(So a user can just press Enter to accept the default.)
In non-interactive mode, this sets the value that will be used
if the user does not explicitly pass --draft or --no-draft.
Tests include all combinations of:
{ interactive, non-interactive } x { --draft, --no-draft, no flag }
Refs #568

submit: add 'spice.submit.draft' to change --draft/--no-draft default

---

.changes/unreleased/Changed-20250706-152414.yaml
branch_submit.go
branch_submit_test.go
doc/includes/cli-reference.md
doc/src/cli/config.md
testdata/script/branch_submit_web_created.txt
testdata/script/branch_submit_web_flag_overrides.txt
testdata/script/stack_submit_web_created_mixed.txt

The --web flag now accepts an argument,
which can be 'true', 'false', or 'created'.
true and false match today's behavior, while 'created'
means that only newly created CRs will be opened in a browser.
For backwards compatibility, the argument is optional:
--web    # equivalent to --web=true
--no-web # equivalent to --web=false
The configuration option `spice.submit.web` also accepts the same values.
Resolves #649

submit/web: set to 'created' to open new CRs only

---

.changes/unreleased/Added-20250706-165936.yaml
doc/includes/cli-reference.md
doc/includes/cli-shorthands.md
testdata/script/upstack_delete.txt
upstack.go
upstack_delete.go

This command allows users to delete all branches above
the current branch in the stack, providing a convenient
way to clean up completed upstack branches.
The implementation leverages the existing branchDeleteCmd
logic while using ListUpstack() to determine which branches
to delete in the upstack scope.
Closes #629

Add upstack delete command

---

.changes/unreleased/Added-20250706-165757.yaml
doc/includes/cli-reference.md
doc/includes/cli-shorthands.md
stack.go
stack_delete.go
testdata/script/stack_delete.txt

This command allows users to delete all branches in the current
branch's stack with a single command, providing a convenient way
to clean up completed or abandoned feature stacks.
The implementation leverages the existing branchDeleteCmd
logic while using ListStack() to determine which branches
to delete in the current stack scope.
Closes #629

Add stack delete command

---

.changes/unreleased/Added-20250708-201239.yaml
doc/includes/cli-reference.md
doc/includes/cli-shorthands.md
repo.go
repo_restack.go
testdata/script/repo_restack_already_restacked.txt
testdata/script/repo_restack_basic.txt
testdata/script/repo_restack_complex.txt
testdata/script/repo_restack_conflicts.txt
testdata/script/repo_restack_edge_cases.txt

Add a 'repo restack' command that restacks all tracked branches.
Branches have to be sorted in topological order
based on their base relationships before being restacked.
Resolves #505

feat: repo restack command

---

.changes/unreleased/Fixed-20250711-212136.yaml
.changes/unreleased/Fixed-20250711-212236.yaml
.changes/unreleased/Fixed-20250711-215056.yaml
branch_squash.go
branch_submit.go
internal/spice/state/storage/git.go
internal/spice/state/storage/git_test.go
log.go
testdata/script/branch_squash_after_manual_rebase.txt
testdata/script/issue731_rebase_update_refs_warnings.txt

This PR fixes a couple issues discovered in trying to fix #731.
First, there's a data race in the Git backend:
when multiple processes try to write to it,
the `update ref` operation can fail.
We accounted for this and retry, but with enough updates,
the operation can actually fail.
To fix this, add locking around the Git backend's read/write operations,
ensuring that only one process can write at a time.
The included test tries to run a bunch of operations on it concurrently,
and fails without the fix.
Secondly, we discovered that in a couple places, including `log long`,
we did `LookupBranch`/`LoadBranches` before calling `VerifyRestacked`.
This means we loaded the branch information (including the base hash)
and then called `VerifyRestacked`, which, despite the read-only-looking name …

fix: concurrent Git storage usage, bad base hash after manual rebase

---

internal/forge/github/testdata/auth/pat.txt
internal/forge/gitlab/testdata/auth/pat.txt

The uitest script here seems to be wrong.
Unclear why we're grabbing the snapshot after sending the keys
instead of before.
I wasn't able to reproduce the flake locally,
but this should fix it.

test(github, gitlab): attempt to unflake PAT auth tests

---

.changes/unreleased/Added-20250712-091644.yaml
repo_init.go
testdata/script/repo_init_trunk_behind.txt

If trunk is behind upstream,
but a local branch is made on top of latest upstream,
and then someone onboards onto git-spice,
restack commands will attempt to replay the upstream commits
when the local branch is rebased on top of trunk.
This guards against that by warning the user
when trunk is behind upstream at initialization time.

repo init: warn if trunk is behind upstream

---

.github/actions/go-cache/action.yml
.github/actions/install-git/action.yml
.github/workflows/ci.yml
.gitignore
mise.toml
script_test.go
tools/ci/test-matrix/config.go
tools/ci/test-matrix/main.go

Running all script tests in one job takes quite a while.
Try sharding them across multiple jobs to speed up CI.

ci: Shard script tests

---

.changes/unreleased/Added-20250716-202212.yaml
doc/includes/cli-reference.md
doc/src/cli/config.md
internal/handler/checkout/handler.go
internal/handler/checkout/handler_test.go
testdata/script/checkout_verbose.txt

This adds a new configuration option that controls whether checkout
navigation commands print verbose messages when switching branches.
The option defaults to true but allows users to opt out.
Resolves #717

checkout: add spice.checkout.verbose config

---

dumpmd.go
internal/git/config.go
internal/git/config_test.go
internal/spice/config.go
internal/spice/config_test.go

For some commands to be implemented correctly,
we need to be able to read Git configuration values.
This commit adds support for reading Git configuration values
by using keys in the form `config:"@core.key"`.
This will read the configuration key `core.key` from git-config,
omitting the "spice." prefix.

cli/config: learn to load Git configuration

---

.changes/unreleased/Changed-20250718-190950.yaml
branch_squash.go
testdata/script/branch_squash_comment_string.txt

"The original commit messages were:", uncommented
becomes part of the commit message itself.
Refs #755

branch squash: Use a template similar to Git

---

.changes/unreleased/Added-20250718-202010.yaml
branch_squash.go
doc/includes/cli-reference.md
internal/handler/squash/handler.go
internal/handler/squash/handler_test.go
testdata/script/branch_squash_no_edit.txt

If set, the message will be generated without comments
and be used as the commit message without opening an editor.
Resolves #755

branch squash: Add --no-edit flag

---

go.mod
go.sum
internal/spice/branch.go
internal/spice/branch_graph.go
internal/spice/branch_graph_test.go
internal/spice/service.go

The branch graph traversals end up loading the same data from disk
several times to try to look up or down the stack.
This introduces a BranchGraph abstraction that loads that data once
and provides read-only access to the graph as iterables.
For backwards compatiblity, the old methods are still available for now.
We may remove them in the future and pass the graph around.
The graph can also be cached using a hash of the store's Git hash,
so the same process can re-use the graph if the store hasn't changed.
(This is not implemented yet.)

internal/spice: unify branch traversals

---

.changes/unreleased/Fixed-20250722-150705.yaml
internal/handler/restack/handler.go
internal/handler/restack/handler_test.go
internal/handler/restack/mocks_test.go
internal/iterutil/iterutil.go
internal/iterutil/iterutil_test.go

Avoid loading the branch graph for the downstack/upstack traversal
during a restack operation by taking advantage of the branch graph.
This won't be a major difference versus reloading
as we're just going from two to one reload.

fix(restack): leverage branch graph to avoid reloading

---

.changes/unreleased/Fixed-20250719-112448.yaml
internal/handler/restack/branch_test.go
internal/handler/restack/handler.go
internal/handler/restack/handler_test.go
internal/handler/restack/mocks_test.go
internal/spice/branch_graph.go
internal/spice/branch_graph_test.go
internal/spice/service.go
internal/spice/service_test.go
testdata/script/stack_restack_skip_worktree.txt

When running stack-scoped operations, if a branch to be restacked
is checked out in another worktree,
skip it instead of failing the command.

fix(restack): worktree aware restack

---

internal/spice/branch_graph.go
internal/spice/restack.go
log.go
testdata/script/log_short_branch_deleted_out_of_band.txt

Fixes a regression introduced in a prior commit
where 'gs ls' would panic if a branch was deleted out of band.
To fix the issue, switch to using the branch graph
which will get rid of out-of-band deleted branches during load.
No changelog entry needed as the regression wasn't released to users yet.

fix(log): Fix regression in deleted branch detection

---

doc/mkdocs.yml
doc/src/start/submit.md

These were originally kept out of the sidebar
because I expected them to have verbose titles
and wanted more flexibility with content and subsections.
I think it's fine to keep them in the sidebar now
as the expected UX of the site is now to have subsections
clearly visible in the sidebar.
Resolves #792

doc: add Get Started subsections to sidebar

---

.changes/unreleased/Added-20250809-105418.yaml
doc/includes/cli-reference.md
doc/src/cli/config.md
doc/src/guide/cr.md
internal/handler/sync/closed_change_behavior_test.go
internal/handler/sync/handler.go
testdata/script/repo_sync_closed_cr_ignore.txt

Introduces a 'spice.repoSync.closedChanges' configuration option
that allows users to opt out of the closed PR detection
added in the previous release
as some users prefer not to delete branches for closed PRs.
Resolves #793

repo sync: add closed PR handling opt-out

---

internal/forge/github/label.go
internal/git/remote_test.go
internal/handler/submit/nav_comment.go
internal/handler/sync/handler.go
internal/spice/branch.go
log.go

Switch to the new WaitGroup.Go method added in Go 1.25.

all: WaitGroup.{Add+Done} => WaitGroup.Go

---

.changes/unreleased/Fixed-20250830-143837.yaml
.changes/unreleased/Fixed-20250830-150221.yaml
internal/handler/list/handler.go
internal/spice/branch_graph.go
log.go
log_long.go
log_short.go
testdata/script/branch_checkout_remote.txt
testdata/script/log_from_untracked_and_detached.txt

Continue the slow migration to the Handler pattern.
Move part of the log command's business logic into a handler.
This better draws the boundary for the upcoming JSON flag.
In porting the code over, I realized that the `isVisible` logic
basically meant that we were querying all branches
and then filtering them in memory at render time.
With the branch graph's new stack querying capabilities,
we're able to avoid querying branches we don't need
when `--all` is not specified.
On a test repository with a 100 branches,
if I run this from a branch that's stacked on top of main,
and has nothing else on top of it (so there won't be a lot to query):
```
❯ hyperfine --warmup 5 'gs ll' '../main/bin/gs ll'
Benchmark 1: gs ll
Time (mean ± σ):     909.0 ms ±  18.0 ms    [User: 2786.6 ms, System: 3248.9 …
```

refac(log): extract into handler

---

log.go
log_test.go

Use a custom iota-based enum for the changeFormat type
instead of string matching
[skip changelog]: no user-visible changes

refac(log/changeFormat): string => enum

---

internal/git/gittest/script.go
internal/git/gittest/version.go
internal/git/gittest/version_test.go
internal/git/merge_tree.go
internal/git/merge_tree_test.go
tools/ci/test-matrix/config.go

This adds a new method `MergeTree` to the `git.Repository` type.
This allows performing merge operations between two branches or trees
without affecting the index or working tree.
In particular, with the --merge-base option (added in Git 2.40),
this allows a differential application of a commit's changes
to another commit or tree.
This feature in particular is useful for implementing
functionality similar to the experimental `git replay` command.

git: add MergeTree method

---

internal/git/index_wt.go
internal/git/index_wt_test.go

Adds a new WriteIndexTree method to git.Worktree
that writes the current index to a new tree object.
This is necessary for implementing low-level operations
on staged changes without committing them.

git: add analog for 'git write-tree'

---

internal/ui/widget/commit.go
internal/ui/widget/commit_pick.go
internal/ui/widget/commit_pick_test.go
internal/ui/widget/testdata/script/commit_pick/basic.txt
internal/ui/widget/testdata/script/commit_pick/branch_without_commit.txt
internal/ui/widget/testdata/script/commit_pick/preselected.txt

This widget presents the branches and commits in a tree-like structure
similar to `gs ll`, allowing users to select a particular commit.
Example:

ui: Add commit selection widget

---

internal/git/commit.go
internal/git/commit_test.go

Adds a Repository.ReadCommit method
that allows reading an almost complete view
of a Commit object by a commit-ish string.
Needed for other functionality in the future.

git: add ReadCommit for Commit object lookup

---

config_test.go
doc/includes/cli-reference.md
doc/mkdocs.yml
doc/src/cli/experiments.md
dumpmd.go
internal/cli/experiment/check.go
internal/cli/experiment/check_test.go
internal/spice/config.go
main.go

Add support for experimental commands in git-spice.
Experimental commands are marked with an "experiment" tag
and can be enabled or disabled via git configuration.
Includes updates to the doc website to list all available experiments
and links between reference and the experiments documentation.

Support experimental commands

---

doc/hooks/freeze.py
doc/mkdocs.yml
doc/pyproject.toml
doc/src/css/custom.css
doc/uv.lock

Uses the `mkdocs-llmstxt` plugin to generate structured documentation files (`llms.txt` and `llms-full.txt`) that LLMs can easily parse and reference.
Currently, these files expose most of the same content as the main documentation site, except for the changelog. Due to plugin limitations, the pages included in `llms.txt` must be explicitly configured. Future plugin versions may allow reusing the nav configuration by default.
To ensure code snippets wrapped in SVGs (created by freeze) are included in the output, we also wrap them in a hidden `<code>` tag. This improves accessibility for both screen readers and allows the plugin generating the `llms.txt` file to include it in its output.
This only a first minimal implementation. Further iterations may be required to ensure cleaner markdown …

docs: Provide llms.txt and llms-full.txt for LLM-friendly documentation

---

.changes/unreleased/Fixed-20250915-194553.yaml
internal.go
internal/git/stash.go
internal/git/stash_test.go
internal/handler/restack/handler.go
main.go
repo_restack.go
testdata/script/issue804_repo_restack_dirty_tree.txt
testdata/script/repo_restack_autostash_apply_conflict.txt
testdata/script/repo_restack_autostash_restack_conflict.txt

Introduces an 'internal' hidden namespace for commands
to be used by operations like popping the stash
after the main operation is complete.
Right now, we're only using this for 'repo restack'.
We may expand this to fully git-spice managed stashing
for restack operations in the future.
Resolves #804

fix(repo restack): autostash dirty changes before restack

---

commit_fixup.go
internal/git/restore_wt.go
internal/git/restore_wt_test.go
internal/handler/fixup/handler.go
internal/handler/fixup/mocks_test.go
testdata/script/commit_fixup_autostash_clean_apply.txt
testdata/script/commit_fixup_autostash_with_upstack_conflict.txt

If there are unstaged changes in the worktree when using commit fixup
to fix up a downstack branch, we should not pop the autostashed changes
until after the upstack restack is complete,
and we've switched back to the original branch (not the fixed branch).
Ref: https://github.com/abhinav/git-spice/discussions/867#discussioncomment-14465048
[skip changelog]: New entry not required as fixup hasn't been released yet.

fix(commit fixup): handle autostashing dirty changes

---

.changes/unreleased/Changed-20250824-204137.yaml
.goreleaser.yml

goreleaser is phasing out formula support in favor of Casks.
Switch to Cask for Homebrew Tap releases.
Ref: https://goreleaser.com/deprecations/#brews
Per docs, should add the following manually to the old formula:
```
disable! date: "2025-11-08", because: "was migrated to a cask", replacement_cask: "abhinav/tap/git-spice"
```

release/homebrew: Publish Cask instead of Formula

---

.goreleaser.yml

binary name is "gs", not "git-spice".
Also, drop conflicts: formula section as that's a no-op per goreleaser.

goreleaser: fix binary name

---

.changes/unreleased/Changed-20251005-201112.yaml
internal/handler/submit/handler.go
testdata/script/branch_submit_zero_commits.txt

When submitting a branch with zero commits compared to its base,
warn the user and prompt for confirmation in interactive mode.
In non-interactive mode, log a warning but continue.
This prevents accidental creation of empty change requests.
Resolves #878

submit: warn and prompt when submitting zero-commit branches
